import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import '../styles/globals.css';

export default function RootLayout({ children }) {
	return (
		<html>
			<head>
				<title>Shitemap.js</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Doto:wght@400;600&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20,300,0,0&icon_names=open_in_new"
				/>
			</head>
			<body>
				<div className={styles.container}>
					<main className={styles.main}>
						<h1 className={styles.title}>Shitemap.js</h1>
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
