import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import '../styles/globals.css';

export default function RootLayout({ children }) {
	return (
		<html>
			<head>
				<title>Shitemap.js</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<div className={styles.container}>
					<main className={styles.main}>
						<h1 className={styles.title}>Shitemap.js</h1>
            			{children}
					</main>
				</div>
			</body>
		</html>
	);
}
